#!/usr/bin/env node
/**
 * One command, one terminal, no stale generated files.
 *
 *   npm run dev [-- --port 4000] [-- --host 127.0.0.1]
 *
 * The old loop asked a contributor to hold three facts at once: `npm run serve`
 * builds CSS *once*, so `npm run watch:css` had to run in a second terminal;
 * and `.github/ISSUE_TEMPLATE/new-entry.yml` and the wizard defaults have to be
 * regenerated by hand after a `_data/schema.yml` edit, or `generate.mjs
 * --check` fails the PR after the push. All three are things the machine can
 * hold instead.
 *
 *   npm run dev
 *     ├─ node scripts/generate.mjs                   once, up front
 *     ├─ tailwindcss --watch                         [css]
 *     ├─ bundle exec jekyll serve --livereload       [jekyll]
 *     └─ watch _data/*.yml → debounce → generate     [gen]
 *
 * `npm run serve` and `npm run watch:css` stay as they are for anyone who wants
 * the pieces. No new dependencies: node:child_process and node:fs only.
 */

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { spawn, spawnSync } from 'node:child_process';

const ROOT = process.cwd();

/** `_data` files the issue template and the wizard defaults are derived from. */
const GENERATED_FROM = ['_data/schema.yml', '_data/site.yml'];

/** Enough quiet after a save that an editor's write-truncate-write is one event. */
const DEBOUNCE_MS = 200;

const COLORS = { css: '[36m', jekyll: '[35m', gen: '[33m' };
const RESET = '[0m';
const useColor = process.stdout.isTTY && !process.env.NO_COLOR;

/** Print a line under a `[label]` prefix so interleaved child output stays readable. */
function log(label, line) {
  const tag = useColor ? `${COLORS[label] ?? ''}[${label}]${RESET}` : `[${label}]`;
  process.stdout.write(`${tag} ${line}\n`);
}

/** Split a child's chunk into lines and prefix each. */
function pipeLines(stream, label) {
  let buffer = '';
  stream.setEncoding('utf8');
  stream.on('data', (chunk) => {
    buffer += chunk;
    const lines = buffer.split('\n');
    buffer = lines.pop() ?? '';
    for (const line of lines) if (line.trim() !== '') log(label, line);
  });
}

const children = [];
let shuttingDown = false;

/** Spawn a long-running child whose output is prefixed with `label`. */
function start(label, command, args) {
  const child = spawn(command, args, {
    cwd: ROOT,
    // stdin is piped and left open rather than ignored: the Tailwind CLI treats
    // EOF on a closed stdin as "stop watching" and exits 0 immediately, which
    // would take the whole session down before Jekyll finished its first build.
    stdio: ['pipe', 'pipe', 'pipe'],
    // Its own process group, so shutdown can signal the group. `bundle exec
    // jekyll serve` is two processes; signalling only the one we spawned leaves
    // the server holding the port after Ctrl-C, and the next `npm run dev`
    // fails with EADDRINUSE.
    detached: true,
  });
  children.push(child);
  pipeLines(child.stdout, label);
  pipeLines(child.stderr, label);
  child.on('exit', (code, signal) => {
    if (shuttingDown) return;
    log(label, `exited (${signal ?? `code ${code}`}) — shutting down`);
    shutdown(code === 0 ? 1 : (code ?? 1));
  });
  child.on('error', (error) => {
    log(label, `could not start ${command}: ${error.message}`);
    shutdown(1);
  });
  return child;
}

/** Kill every child's process group once, then exit. Ctrl-C leaves nothing behind. */
function shutdown(code) {
  if (shuttingDown) return;
  shuttingDown = true;
  for (const child of children) {
    if (child.exitCode !== null || child.signalCode !== null) continue;
    try {
      process.kill(-child.pid, 'SIGTERM');
    } catch {
      // The group is already gone, or this is a platform without process
      // groups; the direct kill below is the fallback either way.
      child.kill('SIGTERM');
    }
  }
  process.exit(code);
}

/** Run `scripts/generate.mjs` synchronously; log what it said. */
function generate() {
  const result = spawnSync(process.execPath, [path.join(ROOT, 'scripts', 'generate.mjs')], {
    cwd: ROOT,
    encoding: 'utf8',
  });
  const output = `${result.stdout ?? ''}${result.stderr ?? ''}`.trim();
  for (const line of output.split('\n')) if (line.trim() !== '') log('gen', line);
  if (result.status !== 0) log('gen', 'generate failed — the issue template may be stale');
}

/** The Tailwind CLI as npm resolves it for the other scripts. */
function tailwindBin() {
  const local = path.join(ROOT, 'node_modules', '.bin', 'tailwindcss');
  return fs.existsSync(local) ? local : 'tailwindcss';
}

/* -------------------------------------------------------------------------- */

const argv = process.argv.slice(2);
const optionOf = (name, fallback) => {
  const at = argv.indexOf(name);
  return at === -1 ? fallback : argv[at + 1];
};
const host = optionOf('--host', '127.0.0.1');
const port = optionOf('--port', '4000');

// Same failure message validate.mjs gives, rather than an ENOENT stack trace.
if (spawnSync('bundle', ['--version'], { stdio: 'ignore' }).status !== 0) {
  console.error(
    'bundler was not found on your PATH.\n' +
      'Install Ruby 3.3+ (e.g. `brew install ruby`), then run `bundle install`.'
  );
  process.exit(1);
}

log('gen', 'regenerating files derived from _data/…');
generate();

start('css', tailwindBin(), ['-i', './assets/css/tailwind.css', '-o', './assets/css/site.css', '--watch']);

start('jekyll', 'bundle', ['exec', 'jekyll', 'serve', '--livereload', '--host', host, '--port', port]);

// fs.watch, not a polling loop: the two files are small and edited by hand, and
// the debounce collapses the write-truncate-write an editor does into one run.
let pending = null;
for (const relative of GENERATED_FROM) {
  const file = path.join(ROOT, relative);
  if (!fs.existsSync(file)) continue;
  fs.watch(file, () => {
    clearTimeout(pending);
    pending = setTimeout(() => {
      log('gen', `${relative} changed`);
      generate();
    }, DEBOUNCE_MS);
  });
}

process.on('SIGINT', () => shutdown(0));
process.on('SIGTERM', () => shutdown(0));

log('jekyll', `serving http://${host}:${port}/ — Ctrl-C stops everything`);
